# Introduction to vectors in three dimensions

In this notebook we explore using the Python library numpy for doing calculations with vectors. We begin by importing the library:

In [1]:
import numpy as np

## Vectors as numpy arrays
Vectors in numpy can be represnted by arrays. It is most convenient to input vectors as a row and use numpy's reshape function to put it in the shape of a column vector. For example, we input the vector

$$ \mathbf{v} = \begin{pmatrix} 1 \\ 0 \\ -1 \end{pmatrix} $$

in the following way:

In [2]:
v = np.array([1, 0, -1]).reshape(3,1)
print(v)

[[ 1]
 [ 0]
 [-1]]


The arguments we sent to reshape are exactly like the dimensions of a matrix. In the code above, we told reshape to take the array we just created and make it have 3 rows and 1 column.

## Vector addition and scalar multiplication
We will now look at how we can add and scalar multiply vectors using numpy. Let's create another vector
$$ \mathbf{u} = \begin{pmatrix} 2 \\ 1 \\ 1 \end{pmatrix} $$
and find $u + v$, $v - u$, $3v$ and $-2u$.

In [3]:
u = np.array([2,1,1]).reshape(3,1)
print("u = ")
print(u)

print("u + v = ")
print(u + v)

print("v - u = ")
print(v - u)

print("3 * v = ")
print(3*v)

print("-2 * u = ")
print(-2*u)

u = 
[[2]
 [1]
 [1]]
u + v = 
[[3]
 [1]
 [0]]
v - u = 
[[-1]
 [-1]
 [-2]]
3 * v = 
[[ 3]
 [ 0]
 [-3]]
-2 * u = 
[[-4]
 [-2]
 [-2]]


## Magnitude of a vector
Numpy has a bunch of built in functions for doing linear algebra, and they have the prefix linalg. For example, we compute the magnitude of a vector with the norm function:

```Python
np.linalg.norm(vector)
```

We compute the magnitude of the vector $\mathbf{u}$ created above, noting that it should be
$$ |\mathbf{u}| = \sqrt{2^2 + 1^2 + 1^2} = \sqrt{6} \approx 2.449489742783178 $$

In [4]:
np.linalg.norm(u)

2.449489742783178

## Exercises
1. Create three vectors $\mathbf{u} = \begin{pmatrix} 1 \\ 1 \\ 0 \end{pmatrix}$, $\mathbf{v} =  \begin{pmatrix} 0 \\ 1 \\ 1 \end{pmatrix}$ and $\mathbf{w} = \begin{pmatrix} -1 \\ 0 \\ -1 \end{pmatrix}$.
1. 
  1. Compute $\mathbf{u} + \mathbf{v} + \mathbf{w}$.
  1. Find $2\mathbf{u} - 3 \mathbf{v} + 2\mathbf{w}$.
1. Find the magnitude of $\mathbf{w} - \mathbf{v}$